name: Deploy Vue 3 App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write # Grant write access to repository contents

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Use Ubuntu
      - name: Checkout code
        uses: actions/checkout@v4

      # Use node 22
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Npm install
      - name: Install dependencies
        run: npm install

      # Build
      - name: Build the app
        run: npm run build

      # Deploy
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure git
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'

          # Create a new branch to hold the deployment
          git checkout -b gh-pages

          # Copy the build files to the root directory
          cp -r dist/* .

          # Commit and push the changes
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force --set-upstream origin gh-pages
